# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_auto_20170827_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='operations',
            field=models.ManyToManyField(blank=True, to='monitor.ActionOperation', verbose_name='ActionOperation'),
        ),
        migrations.AlterField(
            model_name='triggerexpression',
            name='service',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Service', verbose_name='关联服务'),
        ),
        migrations.AlterField(
            model_name='triggerexpression',
            name='service_index',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.ServiceIndex', verbose_name='关联服务指标'),
        ),
        migrations.AlterField(
            model_name='triggerexpression',
            name='trigger',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='monitor.Trigger', verbose_name='所属触发器'),
        ),
    ]
