# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-27 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_auto_20170827_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='host_ip',
            field=models.GenericIPAddressField(verbose_name='IP地址'),
        ),
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(max_length=32, verbose_name='主机名'),
        ),
    ]
