# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_auto_20170828_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='plugin_name',
            field=models.CharField(default='n/a', max_length=64, verbose_name='插件名'),
        ),
    ]
