# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-28 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_service_plugin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='recover_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
