# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 01:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_action_recover_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='operations',
            field=models.ManyToManyField(to='monitor.ActionOperation', verbose_name='ActionOperation'),
        ),
        migrations.AlterField(
            model_name='action',
            name='recover_message',
            field=models.TextField(blank=True, null=True, verbose_name='通知文本'),
        ),
        migrations.AlterField(
            model_name='action',
            name='recover_subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='通知主题'),
        ),
        migrations.AlterField(
            model_name='template',
            name='services',
            field=models.ManyToManyField(to='monitor.Service', verbose_name='服务列表'),
        ),
        migrations.AlterField(
            model_name='template',
            name='triggers',
            field=models.ManyToManyField(to='monitor.Trigger', verbose_name='触发器列表'),
        ),
        migrations.AlterField(
            model_name='triggerexpression',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Service', verbose_name='关联服务'),
        ),
        migrations.AlterField(
            model_name='triggerexpression',
            name='service_index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.ServiceIndex', verbose_name='关联服务指标'),
        ),
        migrations.AlterField(
            model_name='triggerexpression',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monitor.Trigger', verbose_name='所属触发器'),
        ),
    ]
