# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-20 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0011_auto_20170901_1951'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': '动作', 'verbose_name_plural': '动作'},
        ),
        migrations.AlterModelOptions(
            name='actionoperation',
            options={'verbose_name': '操作', 'verbose_name_plural': '操作'},
        ),
        migrations.AlterModelOptions(
            name='eventlog',
            options={'verbose_name': '事件日志', 'verbose_name_plural': '事件日志'},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={'verbose_name': '主机', 'verbose_name_plural': '主机'},
        ),
        migrations.AlterModelOptions(
            name='hostgroup',
            options={'verbose_name': '主机组', 'verbose_name_plural': '主机组'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': '主机维护', 'verbose_name_plural': '主机维护'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '服务', 'verbose_name_plural': '服务'},
        ),
        migrations.AlterModelOptions(
            name='serviceindex',
            options={'verbose_name': '服务指标', 'verbose_name_plural': '服务指标'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': '模板', 'verbose_name_plural': '模板'},
        ),
        migrations.AlterModelOptions(
            name='trigger',
            options={'verbose_name': '触发器', 'verbose_name_plural': '触发器'},
        ),
        migrations.AlterModelOptions(
            name='triggerexpression',
            options={'verbose_name': '触发器表达式', 'verbose_name_plural': '触发器表达式'},
        ),
        migrations.AlterModelTable(
            name='action',
            table='action',
        ),
        migrations.AlterModelTable(
            name='actionoperation',
            table='actionoperation',
        ),
        migrations.AlterModelTable(
            name='eventlog',
            table='eventlog',
        ),
        migrations.AlterModelTable(
            name='host',
            table='host',
        ),
        migrations.AlterModelTable(
            name='hostgroup',
            table='hostgroup',
        ),
        migrations.AlterModelTable(
            name='maintenance',
            table='maintenance',
        ),
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
        migrations.AlterModelTable(
            name='serviceindex',
            table='serviceindex',
        ),
        migrations.AlterModelTable(
            name='template',
            table='template',
        ),
        migrations.AlterModelTable(
            name='trigger',
            table='trigger',
        ),
        migrations.AlterModelTable(
            name='triggerexpression',
            table='triggerexpression',
        ),
    ]
