# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-20 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_auto_20171020_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={},
        ),
        migrations.AlterModelOptions(
            name='actionoperation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='eventlog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='host',
            options={},
        ),
        migrations.AlterModelOptions(
            name='hostgroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
        migrations.AlterModelOptions(
            name='serviceindex',
            options={},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={},
        ),
        migrations.AlterModelOptions(
            name='trigger',
            options={},
        ),
        migrations.AlterModelOptions(
            name='triggerexpression',
            options={},
        ),
        migrations.AlterModelTable(
            name='action',
            table=None,
        ),
        migrations.AlterModelTable(
            name='actionoperation',
            table=None,
        ),
        migrations.AlterModelTable(
            name='eventlog',
            table=None,
        ),
        migrations.AlterModelTable(
            name='host',
            table=None,
        ),
        migrations.AlterModelTable(
            name='hostgroup',
            table=None,
        ),
        migrations.AlterModelTable(
            name='maintenance',
            table=None,
        ),
        migrations.AlterModelTable(
            name='service',
            table=None,
        ),
        migrations.AlterModelTable(
            name='serviceindex',
            table=None,
        ),
        migrations.AlterModelTable(
            name='template',
            table=None,
        ),
        migrations.AlterModelTable(
            name='trigger',
            table=None,
        ),
        migrations.AlterModelTable(
            name='triggerexpression',
            table=None,
        ),
    ]
