# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-20 16:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passcracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssh_crack',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='ssh_crack_detail',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
