# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-17 01:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='arp_HostScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField(verbose_name='主机地址')),
                ('port', models.IntegerField(verbose_name='端口号')),
                ('add_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HostDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.GenericIPAddressField(verbose_name='主机ip')),
                ('host_details', models.CharField(max_length=255, verbose_name='主机详情')),
                ('ip_type', models.CharField(max_length=255, verbose_name='IP类型')),
            ],
        ),
        migrations.CreateModel(
            name='Tcp_HostScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
