# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-11 12:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='验证码')),
                ('email', models.EmailField(max_length=20, verbose_name='邮箱')),
                ('send_type', models.CharField(choices=[('register', '注册'), ('forget', '找回密码')], max_length=10)),
                ('send_time', models.DateTimeField(default=datetime.datetime(2017, 6, 11, 12, 59, 1, 2546))),
            ],
            options={
                'verbose_name_plural': '邮箱验证码',
                'verbose_name': '邮箱验证码',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('userpass', models.CharField(max_length=20, verbose_name='密码')),
                ('image', models.ImageField(default='/static/images/default.jpg', upload_to='image/%Y/%m', verbose_name='图像')),
                ('position', models.CharField(max_length=20, verbose_name='用户职位')),
                ('user_type', models.IntegerField(choices=[(0, 'member'), (1, 'admin'), (2, 'superadmin')], default=0, verbose_name='用户类型')),
            ],
            options={
                'verbose_name_plural': '用户信息',
                'verbose_name': '用户信息',
            },
        ),
    ]
