# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-29 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='software',
            old_name='type',
            new_name='system_type',
        ),
    ]
