# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-30 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20171030_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nic',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
