# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-15 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0005_auto_20171030_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='disk',
            name='slot',
            field=models.IntegerField(blank=True, max_length=64, null=True, verbose_name='插槽位'),
        ),
        migrations.AlterField(
            model_name='server',
            name='update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
