# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-26 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170826_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(max_length=50, verbose_name='用户名'),
        ),
    ]
